apiVersion: v1
kind: Secret
metadata:
  name: c2-svmdest-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c2-nas-backend
  namespace: trident
spec:
  version: 1
  backendName: c2-ontap-nas-backend
  storageDriverName: ontap-nas
  replicationPolicy: MirrorAllSnapshots
  managementLIF: 192.168.0.40
  dataLIF: 192.168.0.41
  svm: svmdest
  credentials:
    name: c2-svmdest-backend-secret
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c2-san-backend
  namespace: trident
spec:
  version: 1
  backendName: c2-ontap-san-backend
  storageDriverName: ontap-san
  replicationPolicy: MirrorAllSnapshots
  managementLIF: 192.168.0.40
  dataLIF: 192.168.0.42
  svm: svmdest
  credentials:
    name: c2-svmdest-backend-secret